apiVersion: v1
data:
  WORDPRESS_CONFIG_EXTRA: |
    define('WP_REDIS_CLIENT', 'predis');
    define('WP_REDIS_SCHEME', 'tcp');
    define('WP_REDIS_HOST', 'wordpress-cache');
    define('WP_REDIS_PORT', '6379');
    define('WP_REDIS_PASSWORD', '');
    define('WP_REDIS_DATABASE', '0');
    define('WP_REDIS_MAXTTL', '900');
    define('WP_REDIS_SELECTIVE_FLUSH', 'xx_');
immutable: false
kind: ConfigMap
metadata:
  name: wordpress-config
